import type { Role } from '../generated/prisma/enums.js';
import {
  PERMISSIONS,
  type Permission,
} from './permissions.js';

export const ROLE_PERMISSIONS = {
  OWNER: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.INVITATIONS_MANAGE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
  ],

  ADMIN: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.INVITATIONS_MANAGE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
  ],

  AGENT: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
  ],

  VIEWER: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.TICKETS_READ,
  ],
} satisfies Record<
  Role,
  readonly Permission[]
>;